In [ ]:
import math

num = 25.7
num2 = 16

print("Floor:", math.floor(num))

Floor: 25


In [ ]:
print(f"Natural log of 10 (ln(10)): {math.log(10)}")
print(f"Log base 10 of 100 (log10(100)): {math.log10(100)}")
print(f"Log base 2 of 8 (log2(8)): {math.log2(8)}")

Natural log of 10 (ln(10)): 2.302585092994046
Log base 10 of 100 (log10(100)): 2.0
Log base 2 of 8 (log2(8)): 3.0


In [ ]:
print(f"Absolute value of -12.5: {math.fabs(-12.5)}")

Absolute value of -12.5: 12.5


In [ ]:
print(f"Factorial of 8: {math.factorial(8)}")

Factorial of 8: 40320


In [ ]:
import math

print(f"2 to the power of 3: {math.pow(2, 3)}")

2 to the power of 3: 8.0


In [ ]:
number_to_round = 8.7
print(f"Rounding {number_to_round}: {round(number_to_round)}")

number_for_remainder = 9
divisor = 4
print(f"Remainder of {number_for_remainder} divided by {divisor}: {number_for_remainder % divisor}")

Rounding 8.7: 9
Remainder of 9 divided by 4: 1


In [ ]:
print(f"Value of pi: {math.pi}")
print(f"Value of e: {math.e}")
print(f"Value of tau: {math.tau}")

Value of pi: 3.141592653589793
Value of e: 2.718281828459045
Value of tau: 6.283185307179586


In [ ]:
print(f"Ceiling of {num}: {math.ceil(num)}")
print(f"Square root of {num2}: {math.sqrt(num2)}")
print(f"Integer square root of {num2}: {math.isqrt(num2)}")

int1 = 48
int2 = 18
print(f"GCD of {int1} and {int2}: {math.gcd(int1, int2)}")

Ceiling of 25.7: 26
Square root of 16: 4.0
Integer square root of 16: 4
GCD of 48 and 18: 6


In [ ]:
import math

angle_degrees = 40
angle_radians = math.radians(angle_degrees)

print(f"Angle in degrees: {angle_degrees}")
print(f"Angle in radians: {angle_radians:.4f}")

print(f"Sine of {angle_degrees} degrees: {math.sin(angle_radians):.4f}")
print(f"Cosine of {angle_degrees} degrees: {math.cos(angle_radians):.4f}")
print(f"Tangent of {angle_degrees} degrees: {math.tan(angle_radians):.4f}")

Angle in degrees: 40
Angle in radians: 0.6981
Sine of 40 degrees: 0.6428
Cosine of 40 degrees: 0.7660
Tangent of 40 degrees: 0.8391


In [ ]:
import math

angle = math.radians(30)

print("Sin:", math.sin(angle))

Sin: 0.49999999999999994


In [ ]:
import math

print("Arc Sin:", math.asin(0.5))

Arc Sin: 0.5235987755982989


In [ ]:
import math

print("Cosh:", math.cosh(1))

Cosh: 1.5430806348152437


In [ ]:
import numpy as np


my_array = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])

print(f"Original Array:\n{my_array}")


print(f"Number of dimensions (ndim): {my_array.ndim}")
print(f"Shape of the array (shape): {my_array.shape}")
print(f"Total number of elements (size): {my_array.size}")
print(my_array.reshape(1,9))
print(np.zeros((2, 3)))

Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Number of dimensions (ndim): 2
Shape of the array (shape): (3, 3)
Total number of elements (size): 9
[[1 2 3 4 5 6 7 8 9]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
import numpy as np

print(f"Original Array:\n{my_array}\n")

print(f"Sum of all elements in the array: {my_array.sum()}\n")
print(f"Sum along axis 0 (columns): {my_array.sum(axis=0)}")
print(f"Sum along axis 1 (rows): {my_array.sum(axis=1)}\n")
print(f"Mean of all elements in the array: {my_array.mean()}\n")
print(f"Mean along axis 0 (columns): {my_array.mean(axis=0)}")
print(f"Mean along axis 1 (rows): {my_array.mean(axis=1)}\n")
array_to_sort = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print(f"Original 1D array for sorting: {array_to_sort}")
sorted_array = np.sort(array_to_sort)
print(f"Sorted 1D array: {sorted_array}\n")
sin_array = np.sin(my_array)
print(f"Array after applying np.sin():\n{sin_array}")

Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sum of all elements in the array: 45

Sum along axis 0 (columns): [12 15 18]
Sum along axis 1 (rows): [ 6 15 24]

Mean of all elements in the array: 5.0

Mean along axis 0 (columns): [4. 5. 6.]
Mean along axis 1 (rows): [2. 5. 8.]

Original 1D array for sorting: [3 1 4 1 5 9 2 6]
Sorted 1D array: [1 1 2 3 4 5 6 9]

Array after applying np.sin():
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]


In [ ]:
import math

num1 = 24
num2 = 36
print(f"The GCD of {num1} and {num2} is: {math.gcd(num1, num2)}")

The GCD of 24 and 36 is: 12


In [ ]:
import numpy as np
from scipy.linalg import det, eig

matrix = np.array([[3, 2], [1, 4]])
print(f"Original Matrix:\n{matrix}\n")

determinant = det(matrix)
print(f"Determinant of the matrix: {determinant}\n")

eigenvalues, eigenvectors = eig(matrix)

print(f"Eigenvalues of the matrix: {eigenvalues}")
print(f"Eigenvectors of the matrix:\n{eigenvectors}")

Original Matrix:
[[3 2]
 [1 4]]

Determinant of the matrix: 10.0

Eigenvalues of the matrix: [2.+0.j 5.+0.j]
Eigenvectors of the matrix:
[[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


In [ ]:
import numpy as np

my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
print(f"Original Python List: {my_list}")

array_1d = np.array(my_list)
print(f"\n1D NumPy Array: {array_1d}")
print(f"Shape of 1D array: {array_1d.shape}")

array_2d = array_1d.reshape(3, 4)
print(f"\nReshaped 2D Array (3x4):\n{array_2d}")
print(f"Shape of 2D array: {array_2d.shape}")

array_3d = array_1d.reshape(2, 2, 3)
print(f"\nReshaped 3D Array (2x2x3):\n{array_3d}")
print(f"Shape of 3D array: {array_3d.shape}")

Original Python List: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

1D NumPy Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Shape of 1D array: (12,)

Reshaped 2D Array (3x4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape of 2D array: (3, 4)

Reshaped 3D Array (2x2x3):
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape of 3D array: (2, 2, 3)


In [ ]:
import math

num_n_perm = 6
num_k_perm = 3
permutation_result = math.perm(num_n_perm, num_k_perm)
print(f"The permutation of {num_n_perm} and {num_k_perm} is: {permutation_result}")


num_n_comb = 5
num_k_comb = 2
combination_result = math.comb(num_n_comb, num_k_comb)
print(f"The combination of {num_n_comb} and {num_k_comb} is: {combination_result}")

The permutation of 6 and 3 is: 120
The combination of 5 and 2 is: 10


In [ ]:
import math

num1 = 20

num2 = 15

num3 = 35

lcm_result = math.lcm(num1, num2, num3)

print(f"The LCM of {num1}, {num2}, and {num3} is: {lcm_result}")

The LCM of 20, 15, and 35 is: 420


In [ ]:
import pandas as pd
data = {
    "Name":["Rashi","Aryan","Rishab","Aman","Ayush","Lovely","Madhu","Sabila","Pretti","Sheela"],
    "Age":[20,21,22,19,20,29,25,26,25,23],
    "Marks":[99,90,78,37,90,75,89,98,93,88]
}

df1 = pd.DataFrame(data)
print(df1)

     Name  Age  Marks
0   Rashi   20     99
1   Aryan   21     90
2  Rishab   22     78
3    Aman   19     37
4   Ayush   20     90
5  Lovely   29     75
6   Madhu   25     89
7  Sabila   26     98
8  Pretti   25     93
9  Sheela   23     88


In [ ]:
import math

print(f"e to the power of 1: {math.exp(1)}")
print(f"e to the power of 2: {math.exp(2)}")

e to the power of 1: 2.718281828459045
e to the power of 2: 7.38905609893065


In [ ]:
def grade(m):
    if m > 80:
        return "A"
    elif m >= 60:
        return "B"
    else:
        return "C"

df1["Grade"] = df1["Marks"].apply(grade)
print(df1)

     Name  Age  Marks Grade
0   Rashi   20     99     A
1   Aryan   21     90     A
2  Rishab   22     78     B
3    Aman   19     37     C
4   Ayush   20     90     A
5  Lovely   29     75     B
6   Madhu   25     89     A
7  Sabila   26     98     A
8  Pretti   25     93     A
9  Sheela   23     88     A


In [ ]:
import numpy as np
df1["Roll No"] = np.random.permutation(range(1,len(df1)+1))
print(df1)

     Name  Age  Marks Grade  Roll No
0   Rashi   20     99     A        7
1   Aryan   21     90     A        8
2  Rishab   22     78     B        2
3    Aman   19     37     C        5
4   Ayush   20     90     A        1
5  Lovely   29     75     B        6
6   Madhu   25     89     A       10
7  Sabila   26     98     A        9
8  Pretti   25     93     A        4
9  Sheela   23     88     A        3


In [ ]:
print(len(df1))

10


In [ ]:
random_nums = np.random.choice(range(60, 121), size=len(df1), replace=False)

# Format them
df1["Roll No"] = ["23CS2011" + str(i).zfill(3) for i in random_nums]

print(df1)

     Name  Age  Marks Grade      Roll No
0   Rashi   20     99     A  23CS2011072
1   Aryan   21     90     A  23CS2011099
2  Rishab   22     78     B  23CS2011101
3    Aman   19     37     C  23CS2011113
4   Ayush   20     90     A  23CS2011094
5  Lovely   29     75     B  23CS2011106
6   Madhu   25     89     A  23CS2011083
7  Sabila   26     98     A  23CS2011104
8  Pretti   25     93     A  23CS2011081
9  Sheela   23     88     A  23CS2011071


In [ ]:
import pandas as pd
import numpy as np
data = {
    "Name":["Sakshi","Priya","Alisha"],
    "Age":[28,24,20],
    "Marks":[87,94,90]
}

df2 = pd.DataFrame(data)
print(df2)

     Name  Age  Marks
0  Sakshi   28     87
1   Priya   24     94
2  Alisha   20     90


In [ ]:
def grade(m):
    if m > 80:
        return "A"
    elif m >= 60:
        return "B"
    else:
        return "C"

df2["Grade"] = df2["Marks"].apply(grade)
print(df2)

     Name  Age  Marks Grade
0  Sakshi   28     87     A
1   Priya   24     94     A
2  Alisha   20     90     A


In [ ]:
random_nums = np.random.choice(range(60, 121), size=len(df2), replace=False)

# Format them
df2["Roll No"] = ["23CS2011" + str(i).zfill(3) for i in random_nums]

print(df2)

     Name  Age  Marks Grade      Roll No
0  Sakshi   28     87     A  23CS2011096
1   Priya   24     94     A  23CS2011063
2  Alisha   20     90     A  23CS2011104


In [ ]:
df = pd.concat([df1, df2], ignore_index=True)
print(df)

      Name  Age  Marks Grade      Roll No
0    Rashi   20     99     A  23CS2011072
1    Aryan   21     90     A  23CS2011099
2   Rishab   22     78     B  23CS2011101
3     Aman   19     37     C  23CS2011113
4    Ayush   20     90     A  23CS2011094
5   Lovely   29     75     B  23CS2011106
6    Madhu   25     89     A  23CS2011083
7   Sabila   26     98     A  23CS2011104
8   Pretti   25     93     A  23CS2011081
9   Sheela   23     88     A  23CS2011071
10  Sakshi   28     87     A  23CS2011096
11   Priya   24     94     A  23CS2011063
12  Alisha   20     90     A  23CS2011104


In [ ]:
print(df.sort_values(by="Marks", ascending=False))

      Name  Age  Marks Grade      Roll No
0    Rashi   20     99     A  23CS2011072
7   Sabila   26     98     A  23CS2011104
11   Priya   24     94     A  23CS2011063
8   Pretti   25     93     A  23CS2011081
1    Aryan   21     90     A  23CS2011099
4    Ayush   20     90     A  23CS2011094
12  Alisha   20     90     A  23CS2011104
6    Madhu   25     89     A  23CS2011083
9   Sheela   23     88     A  23CS2011071
10  Sakshi   28     87     A  23CS2011096
2   Rishab   22     78     B  23CS2011101
5   Lovely   29     75     B  23CS2011106
3     Aman   19     37     C  23CS2011113


In [ ]:
from collections import Counter

def count_char_frequency(input_string):
    """Counts the frequency of each character in a string if its length is > 50."""
    if len(input_string) <= 50:
        print(f"String length ({len(input_string)}) is not more than 50. Skipping character frequency count.")
        return {}

    return Counter(input_string)


In [ ]:

long_string = "This is a very long string that definitely has more than fifty characters in it, so it should be processed."

print(f"\nString: '{long_string}'")
long_string_frequency = count_char_frequency(long_string)
if long_string_frequency:
    print("Character frequency (long string):")
    for char, count in long_string_frequency.items():
        print(f"'{char}': {count}")


short_string = "This is a short string."

print(f"\nString: '{short_string}'")
short_string_frequency = count_char_frequency(short_string)
if short_string_frequency:
    print("Character frequency (short string):")
    for char, count in short_string_frequency.items():
        print(f"'{char}': {count}")


String: 'This is a very long string that definitely has more than fifty characters in it, so it should be processed.'
Character frequency (long string):
'T': 1
'h': 6
'i': 9
's': 9
' ': 19
'a': 6
'v': 1
'e': 8
'r': 6
'y': 3
'l': 3
'o': 5
'n': 5
'g': 2
't': 9
'd': 3
'f': 3
'm': 1
'c': 3
',': 1
'u': 1
'b': 1
'p': 1
'.': 1

String: 'This is a short string.'
String length (23) is not more than 50. Skipping character frequency count.


In [ ]:
def remove_duplicates_without_set(input_list):
    unique_list = []
    for item in input_list:
        if item not in unique_list:
            unique_list.append(item)
    return unique_list


my_list = [1, 2, 2, 3, 4, 4, 5, 1]
cleaned_list = remove_duplicates_without_set(my_list)
print(f"Original list: {my_list}")
print(f"List with duplicates removed: {cleaned_list}")

Original list: [1, 2, 2, 3, 4, 4, 5, 1]
List with duplicates removed: [1, 2, 3, 4, 5]
